### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by loisatwood** [seoscribe/glossary#1]
kay, so i have two questions:

- can i use jquery?
- what will be searchable, blog articles, forums... everything?

**Comment by wnda** [comment]
You can use jQuery if you want. Just don't expect me to merge until you've refactored it to vanilla. 😉

Joking aside, see [this mock-up for client-side search](https://github.com/wnda/jsearch/blob/master/search.js) I made for another project which wasn't used in the end.

You will need to alter the manner in which it works. For starters, with the SEO Scribe website, there's no need to generate the search bar on the fly, it's already in the markup. You just need to get rid of the dynamically injected CSS and HTML and reference the actual search bar elements in the main variables.

Also won't need to click in order to show form, but that's just an event listener with some style changes. They're all separate functions so they're easy to remove without effecting the core search.

The reason I suggest to *not* use jQuery, aside from the fact that I thoroughly dislike jQuery in this privileged modern world of high ES5 coverage, it will be **much** slower at calculating Levenshtein distance, the search algo that powers this method.

So, as I said, use jQuery if you want to get a feel for my approach or come up with a better one. If you think you have a better approach, I will rewrite it in vanilla myself.

[Also, see my conversation regarding chat.](https://github.com/seoscribe/editor/issues/3)
